            - name: run-cmake
  # You may pin to the exact commit or the version.
  # uses: lukka/run-cmake@2ce8982be71b8e9a3c4d5e432135035afd1e76a7
  uses: lukka/run-cmake@v10.7
  with:
    # Path to CMakeLists.txt.
    cmakeListsTxtPath: # optional, default is ${{ github.workspace }}/CMakeLists.txt
    # The name of the workflow preset. Optional, it cannot be used with any other preset input. This value is stored in the WORKFLOW_PRESET_NAME environment variable, and used by the default value of 'workflowPresetCmdString' input.
    workflowPreset: # optional, default is 
    # The name of the configure preset. Optional, but at least one of the preset input must be provided. This value is stored in the CONFIGURE_PRESET_NAME environment variable, and used by the default value of 'configurePresetCmdString' input.
    configurePreset: # optional, default is 
    # The name of the build preset. Optional, but at least one of the preset input must be provided. This value is stored in the BUILD_PRESET_NAME environment variable, and used by the default value of 'buildPresetCmdString' input.'
    buildPreset: # optional, default is 
    # The name of the test preset (ctest). Optional, but at least one of the preset input must be provided. This value is stored in the TEST_PRESET_NAME environment variable, and used by the default value of 'testPresetCmdString' input.'
    testPreset: # optional, default is 
    # The name of the package preset (cpack). Optional, but at least one of the preset input must be provided. This value is stored in the PACKAGE_PRESET_NAME environment variable, and used by the default value of 'packagePresetCmdString' input.'
    packagePreset: # optional, default is 
    # A string representing list of additional arguments for configuring. Optional. Useful when specifing additional variables such as, e.g., ['-DVARIABLE=NAME', '-DANOTHERVARIABLE=ANOTHERNAME']
    configurePresetAdditionalArgs: # optional, default is []
    # A string representing list of additional arguments for building. Optional. Useful when specifing the config to build with a multi configuration generator, e.g., ['--config DEBUG']
    buildPresetAdditionalArgs: # optional, default is []
    # A string representing list of additional arguments for testing. Optional. Useful when specifing the config to test with a multi configuration generator, e.g., ['--config DEBUG']
    testPresetAdditionalArgs: # optional, default is []
    # A string representing list of additional arguments for cpack. Optional.
    packagePresetAdditionalArgs: # optional, default is []
    # Specify which shell to be used when launching commands. 'true' means the default shell is used. 'false' means no shell is used. It also can be an absolute with arguments of the shell to spawn commands with.
    useShell: # optional, default is true
    # Specifies a semicolon separated list of regular expressions that are used to identify log file paths in the workflow output. A regular expression must have a single capturing group, that is a single pair of parenthesis such as 'See also (.+.log)'. When a match occurs, the content of the file is written into the workflow output for disclosing its content to the user. The default regular expressions are for CMake's and vcpkg's log files.
    logCollectionRegExps: # optional, default is \s*"(.+CMakeOutput\.log)"\.\s*;\s*"(.+CMakeError\.log)"\.\s*;\s*(.+out\.log)\s*;\s+(.+err\.log)\s*;\s*(.+vcpkg.+\.log)\s*
    # The CMake command format string to run the workflow steps.
    workflowPresetCmdString: # optional, default is [`--workflow`, `--preset`, `$[env.WORKFLOW_PRESET_NAME]`, `--fresh`]
    # The CMake command format string to configure and generate project files.
    configurePresetCmdString: # optional, default is [`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]
    # The CMake command format string to run the build.
    buildPresetCmdString: # optional, default is [`--build`, `--preset`, `$[env.BUILD_PRESET_NAME]`]
    # The CTest command format string to run test.
    testPresetCmdString: # optional, default is [`--preset`, `$[env.TEST_PRESET_NAME]`]
    # The CPack command format string to package the project.
    packagePresetCmdString: # optional, default is [`--preset`, `$[env.PACKAGE_PRESET_NAME]`]
    # Specify the command line to dump the environment variables with the 'vcpkg env' command. This command is only used when setting up the environment for MSVC on Windows.
    runVcpkgEnvFormatString: # optional, default is [`env`, `--bin`, `--include`, `--tools`, `--python`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`, `set`]
          
